export const MAXIMUM_NUMBER_OF_CHOICES = 4;
export const MINIMUM_NUMBER_OF_CHOICES = 2;
export const MINIMUM_NUMBER_OF_POINTS = 0;
export const MAXIMUM_NUMBER_OF_POINTS = 100;
export const VALID_QUESTION_TYPE = 'QCM';
export const MULTIPLE_IDENTIFIER = 10;
