export enum GameEvents {
    RoomMessage = 'roomMessage',
    CreateRoom = 'createRoom',
    CreateRoomRandom = 'createRoomRandom',
    GetRandom = 'getRandom',
    JoinRoom = 'joinRoom',
    Login = 'login',
    Logout = 'logout',
    UpdateRoom = 'updateRoom',
    UpdateUsers = 'updateUsers',
    BanUser = 'banUser',
    AddAnswer = 'addAnswer',
    GetStats = 'getStats',
    DestroyRoom = 'destroyRoom',
    GetUserInfo = 'getUserInfo',
    LockRoom = 'lockRoom',
    UnlockRoom = 'unlockRoom',
    StartGame = 'startGame',
    GetAnswers = 'getAnswers',
    NextQuestion = 'nextQuestion',
    RoundOver = 'roundOver',
    EndGame = 'endGame',
    ConfirmAnswer = 'confirmAnswer',
    SendMessage = 'sendMessage',
    GetAllMessages = 'getAllMessages',
    IsAnswerValid = 'isAnswerValid',
    UpdatePlayerState = 'updatePlayerState',
    MutePlayer = 'mutePlayer',
    PauseTimer = 'pauseTimer',
    PanicMode = 'panicMode',
    SendTextAnswer = 'sendTextAnswer',
    GetTextAnswers = 'getTextAnswers',
    GivePoints = 'givePoints',
    EndCorrection = 'endCorrection',
    ChangeQrlQuestion = 'changeQrlQuestion',
    MakeUserActive = 'makeUserActive',
}

export enum GameClientEvents {
    JoinedRoom = 'joinedRoom',
    LeftRoom = 'leftRoom',
    RoomClosed = 'roomClosed',
    GetAnswers = 'getAnswers',
    GetStats = 'getStats',
    ChangeQuestion = 'changeQuestion',
    FinalizeAnswers = 'finalizeAnswers',
    ShowResults = 'showResults',
    EndRound = 'endRound',
    AnswerChange = 'answerChange',
    GameStarted = 'gameStarted',
    GameStartResponse = 'gameStartResponse',
    PlayerStateChange = 'playerStateChange',
    PlayerMuted = 'playerMuted',
    Tick = 'tick',
    PanicEnabled = 'panicEnabled',
    CorrectQrlQuestions = 'correctQrlQuestions',
}

export enum GameEnum {
    ROOMCODELENGTH = 4,
    Organizer = 'organisateur',
    ErrorMessage = "La salle n'existe pas ou est fermée",
    UserNotValidMessage = "Ce nom d'utilisateur n'est pas valide",
    RoomDoesNotExistMessage = "La salle n'existe pas",
    CantStartGame = 'Impossible de démarrer le jeu.',
    OnlyOrganizerCanStart = "Seul l'organisateur peut démarrer le jeu.",
    RoomLockedOrEmpty = 'Assurez-vous que la salle est verrouillée et non vide.',
}
