/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
/* tslint:disable:object-literal-key-quotes*/

export const Choice = t.iface([], {
    text: 'string',
    isCorrect: t.opt(t.union('boolean', 'null')),
});

export const Question = t.iface([], {
    type: 'string',
    text: 'string',
    points: 'number',
    choices: t.opt(t.array('Choice')),
});

export const Quiz = t.iface([], {
    id: 'string',
    visible: 'boolean',
    title: 'string',
    description: 'string',
    duration: 'number',
    lastModification: 'string',
    questions: t.array('Question'),
});

export const QuizEnum = t.enumtype({
    QCM: 'QCM',
    QRL: 'QRL',
    RANDOMMODE: 'Mode Al\u00E9atoire',
    RANDOMDESCRIPTION: 'Questions al\u00E9atoires',
    IDHEX: '0123456789',
});

const exportedTypeSuite: t.ITypeSuite = {
    Choice,
    Question,
    Quiz,
    QuizEnum,
};
export default exportedTypeSuite;
